sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t kaganberk/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kaganberk/docker-react npm run test
	